apiVersion: v1
kind: Namespace
metadata:
  name: pricebrain
  labels:
    app.kubernetes.io/name: pricebrain
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: pricebrain-infra
  labels:
    app.kubernetes.io/name: pricebrain-infra
    app.kubernetes.io/managed-by: kubectl
